# Generated by Django 6.0.4 on 2026-04-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
